
import React from 'react';
import { LEADERSHIP } from '../data/mockData';
import type { LeadershipMember } from '../types';
import BeliefAccordion from '../components/BeliefAccordion';
import SubNav from '../components/SubNav';
import FadeInOnScroll from '../components/FadeInOnScroll';

const LeadershipCard: React.FC<{ member: LeadershipMember }> = ({ member }) => (
    <div className="text-center">
        <img src={member.imageUrl} alt={member.name} className="w-48 h-48 mx-auto rounded-full object-cover shadow-lg" />
        <h3 className="mt-4 font-header font-extrabold text-2xl">{member.name}</h3>
        <p className="font-accent italic text-brand-primary text-xl">{member.role}</p>
        <p className="mt-2 text-gray-600 text-sm">{member.bio}</p>
    </div>
);

const AboutUsPage: React.FC = () => {
    const beliefs = [
        { title: "The Trinity", content: "We believe in one personal God who created the universe and exists eternally in three distinct persons: Father, Son, and Holy Spirit, who are equal in power, authority, and glory. They are so pure and so united, they operate as one. We believe God is a being of unimaginably wonderful power, goodness, and love.\n\nThis relational God invites us into community that reflects His nature at its core. The Trinity models perfect relationship where each person honors the others while maintaining distinct identity—a pattern for how we engage with one another authentically, with strength and honor. Through understanding God's relational essence, we discover that authentic connection creates invitational communities that love genuinely, embrace truth, and communicate directly." },
        { title: "Jesus Christ", content: "We believe Jesus Christ is the Son of God who laid aside His divine privileges to become human. Born of a virgin, He lived a perfect life of love, bringing the kingdom of heaven to earth. Jesus died on the cross to pay for the sins of the world, was buried, and rose again bodily on the third day. He ascended to heaven and is seated at the right hand of the Father. Jesus is our master, teacher, savior, and friend who now reigns forever with the Father and the Holy Spirit.\n\nWe affirm that Jesus is both fully God and fully man—the image of the invisible God, the firstborn over all creation. In Him all things were created, all things hold together, and through Him all things will be reconciled to God. Through Jesus' finished work, complete salvation, complete healing, and complete deliverance become available to every believer. He loves us and paid for everything we need, opening the way for wholeness in every area of life—spiritually, emotionally, physically, and relationally." },
        { title: "The Holy Spirit", content: "We believe in the Holy Spirit who constitutes the third person of the Trinity—fully God, co-equal with the Father and Son, possessing all divine attributes while demonstrating genuine personality through thinking, feeling, speaking, and making decisions. The Holy Spirit invites us into authentic partnership rather than demanding religious performance, creating space for genuine relationship that reflects God's relational nature.\n\nThe Spirit regenerates and indwells every believer in Jesus, revealing Jesus, guiding us into truth, and empowering us for daily living. He provides supernatural gifts to equip the Church for ministry and gives us a foretaste of eternal life. The Spirit can be closer to us than the air we breathe, transforming us to be like Jesus and enabling us to effectively impact the world with heaven's goodness.\n\nWe believe in a distinct experience of Spirit baptism available to all believers, separate from salvation yet essential for empowered witness. This encounter positions believers to step into their calling through supernatural enablement while maintaining dependence on the Spirit rather than human ability. The same power that raised Jesus from the dead is available to believers today, making the miraculous normal rather than exceptional, enabling partnership with the Holy Spirit that breaks free from religious bondage to live supernaturally instead of remaining trapped in sin's brokenness." },
        { title: "Scripture", content: "We believe that the scriptures of the Old and New Testaments are the inspired written expression of God and, as such, are authoritative. The Bible reveals who God is and is intended to bring us into relationship with Him. Scripture stands as the ultimate authority in all matters of faith and practice, serving as our unique and authoritative guide.\n\nWe believe God divinely inspired the original authors through the Holy Spirit, making Scripture both true and authoritative. While God continues to be present with us, always revealing, He never contradicts what the Scriptures have penned for us. Therefore, Scripture serves not only as inspiration into the life of God, but also as a guardrail for us to know the will of God and test the veracity of all things. All teaching must be firmly rooted in sound biblical exegesis, with Scripture interpreting Scripture and clear passages illuminating the less clear.\n\nCultural trends and human reasoning must submit to biblical revelation. The Bible is both historically accurate and spiritually transformative—living and active, not merely a historical document. Through daily interaction with God in His Word, along with worship and prayer, we forge a kingdom mindset that allows us to live loved and stand firm in who we are in Christ." },
        { title: "Humanity & The Fall", content: "We believe that all people were created in the image of God to enjoy fellowship with Him, giving every person inherent dignity and worth beyond measure. God's original creation was an uncorrupted place of human flourishing through union with God and one another. Inherent in every person is great value and destiny, reflecting God's creative character and relational design as culture makers who reflect His image.\n\nYet humanity willfully rejected the Lordship and glory of God, attempting to be our own gods. Because of this fall into sin, sickness, death and judgment entered the world, and creation now experiences the effects and consequences of sin. Human beings are estranged from God, from each other, from ourselves, and from creation. This brokenness affects every area of life—spiritually, emotionally, physically, and relationally—creating the need for complete restoration and redemption." },
        { title: "Salvation", content: "We believe that the blood of Jesus Christ, which He shed on the cross, provides the only way for the forgiveness of sin and restoration with God. God freely grants salvation to all who place their faith in Jesus, receiving His death and resurrection as sufficient payment for their sin. Salvation cannot be earned; this gift of grace enables wholeness in every area of life.\n\nWe understand salvation as a past, present, and future reality:\nPast: We have been saved by grace through faith—a finished work accomplished by Christ that establishes our identity as beloved children\nPresent: We are being saved as the Holy Spirit transforms us into Christ's likeness, enabling supernatural living through divine partnership\nFuture: We will be saved as God completes His work of redemption in the resurrection of our bodies and the renewal of all creation\n\nFor the salvation of lost and sinful people, regeneration by the Holy Spirit is absolutely essential. This transformation enables us to live from abundance rather than lack, developing an inheritance mindset rather than an orphan mentality that recognizes our position of having what we need through Christ's finished work." },
        { title: "The Gospel", content: "The Gospel represents the good news that God himself, the Creator, has come to rescue us from sin, and renew all things, in and through the work of Jesus Christ on our behalf, to establish his Kingdom, through his people, in the power of the Holy Spirit.\n\nThis good news encompasses the great story of Scripture in four movements:\nCreation: God's original design for human flourishing through relationship\nFall: Humanity's rebellion and the corruption of creation\nRedemption: God's rescue plan culminating in Jesus' death and resurrection\nRenewal: God's promise to restore all creation under Christ's lordship\n\nWe believe the Gospel of Jesus Christ represents the only hope for humankind, speaking to the whole person and capable of transforming anyone anywhere. The good news extends beyond individual hearts to encompass all of creation, demonstrating that the Gospel is for all things. We model and share the life of Christ through servood and bold generosity, ensuring our friends, families, and communities know the powerful love and salvation of Jesus through both words and actions that demonstrate heaven's reality on earth." },
        { title: "The Church", content: "We believe in the universal Church, a diverse assembly of individuals from all races, languages, and countries who have faith in Jesus. The Church represents the community through which God wants to bring love, healing, and growth to the human race, inviting everyone who is willing to follow Jesus. Rather than being merely an institution, the Church functions as the body of Christ, with Jesus as its head.\n\nWe believe in the spiritual unity of believers in our Lord Jesus Christ, the communion of saints, and the holy catholic (universal) church. Through authentic community, we create invitational and strong fellowships that love genuinely, embrace truth, and communicate directly. When conflicts arise, we choose reconciliation over division, celebrating diversity and creating spaces where everyone can belong before they believe.\n\nThe Church operates under Spirit-led, elder-governed leadership where a plurality of qualified elders provides spiritual oversight and protection. Leadership remains character-based rather than merely gift-based, with biblical qualifications for elders being non-negotiable. All believers have access to spiritual gifts, particularly prophecy, which builds up, encourages, and comforts according to biblical pattern, enabling everyone to discover and exercise their unique contribution to the body." },
        { title: "The Kingdom Of God", content: "We believe God does not intend for sin and suffering to get the last word but is at work to redeem and reconcile what He has made. We live in the tension of the Kingdom \"now and not yet,\" praying for His Kingdom to come on earth as it is in heaven while we actively participating in its advancement through supernatural ministry and cultural engagement.\n\nThe Kingdom operates through believers who serve with God in their unique and personal way, ministering to the world with excellence while standing firm in the truth that there is no spectator Christianity. Each person carries God-given purpose that, when fulfilled, brings deep satisfaction and impacts the kingdom. We engage culture as creative makers rather than mere critics, offering alternatives that reflect heaven's values while recognizing that every person has great value and destiny within God's design.\n\nThere exists no square inch in the whole domain of our human existence over which Christ, who is Sovereign over all, does not cry: \"Mine!\" This comprehensive claim challenges us to engage culture creatively rather than merely critique what exists, creating pathways for everyone to contribute meaningfully while celebrating the diverse ways God's image is reflected through each person." },
        { title: "The Return Of Christ", content: "We believe in the personal, visible return of Jesus to establish His Kingdom on earth. Upon Christ's return, He will bring judgment, separate the righteous from the unrighteous, renew the earth, and reign as King forever. We believe in the resurrection of both the saved and the lost—they that are saved unto the resurrection of life and they that are lost unto the resurrection of damnation.\n\nWe believe God is creating a New Heaven and a New Earth where humans will dwell forever with God. This hope inspires godly living and commitment to the Gospel mission while we actively participate in cultural renewal and creative calling that reflects our identity as culture makers who bear God's image through pursuing excellence without compromise in our various spheres of influence." },
        { title: "Women In Leadership", content: "We believe God gifts both women and men to serve in ministry, including exercising leadership gifts as elder, pastor, teacher, and other ministry roles. We embrace an egalitarian approach that values the contributions of all believers according to their calling and gifting rather than gender.\n\nWe believe that women and men are created equal in the image of God, and that God gives leadership in the church based on grace, calling, spiritual gifts, obedience, and character. Both women and men can and should lead, preach, pastor, and minister within the church, as their partnership results in more robust ministry of love and grace that reflects the diverse ways God's image is expressed through His people while creating communities that honor both strength and vulnerability." },
        { title: "Marriage & Sexuality", content: "We believe in the historically Christian view of marriage and sexual expression; namely, that marriage represents a lifelong one-flesh covenant union between two sexually different persons (male and female) from different families, and that all sexual practice outside of marriage constitutes sin.\n\nHowever, we express this belief with the heart of Jesus—welcoming all people regardless of sexual practice or orientation to worship with us. Our doors and arms remain open to anyone, as we seek to be a community where those who may be out-of-alignment with certain teachings still feel welcome and accepted in our fellowship. We differentiate between agreement and acceptance, following Jesus' example of radical love and compassion while creating spaces for authentic connection that honors both truth and grace.\n\nWe lead with love and compassion for people, creating environments where everyone can belong before they believe. Our first responsibility involves being a living display of covenant love and sexuality rather than critiquing the surrounding culture, forming a distinct counterculture where \"life to the full\" becomes visible as an invitation to all who seek authentic relationship and community." },
        { title: "Spiritual Formation & Discipleship", content: "We believe spiritual formation represents the primary focus of the Christian life, balancing theological depth with practical, accessible application. Through daily interaction with God in worship, prayer, and reading the Word, we forge a kingdom mindset that enables us to live loved and stand firm in who we are in Christ. This relationship creates space for transformation that happens naturally when we encounter God's presence personally.\n\nDiscipleship functions as apprenticeship to Jesus in kingdom living, emphasizing character transformation over religious activity. Spiritual disciplines create space for God's transforming work, presenting salvation as participation in God's life rather than merely forgiveness of sins. We establish daily rhythms that create space to connect with God, approaching worship as relationship rather than religious duty while prioritizing God's presence over programs and performance.\n\nThe Holy Spirit transforms character through the nine-fold fruit: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control. This transformation flows through divine enablement rather than human effort, creating authentic change from the inside out rather than external conformity to religious expectations. Walking in the Spirit requires moment-by-moment partnership rather than striving for perfection through willpower alone." },
        { title: "Supernatural Ministry & Spiritual Gifts", content: "We believe all spiritual gifts remain active and necessary for the contemporary church, functioning as tools for building up the body of Christ and extending God's kingdom beyond the church walls. The nine gifts of the Spirit—revelation gifts (word of wisdom, word of knowledge, discerning of spirits), power gifts (faith, healing, miracles), and utterance gifts (prophecy, tongues, interpretation)—operate as the Spirit wills for the common good.\n\nPartnership with the Holy Spirit enables believers to break free from religious bondage and live supernaturally instead of remaining trapped in sin's brokenness. We expect God to work in and through us in ways that exceed natural explanation, developing spiritual alertness to hear God's voice and respond to His leading. Every believer can participate in spiritual gifts, particularly prophecy, which builds up the church and demonstrates God's power while serving practical purposes in ministry and relationship.\n\nWe pray boldly for healing, miracles, and breakthrough while balancing supernatural expectation with biblical wisdom and character development. The same power that raised Jesus from the dead is available to believers today, making the miraculous normal rather than exceptional while maintaining proper order through biblical guidelines and elder oversight that protects the congregation from confusion or manipulation." },
        { title: "Cultural Engagement & Mission", content: "We believe the Holy Spirit empowers bold evangelism and confirms the Gospel through supernatural demonstrations that combine words and actions in everyday contexts. The same Spirit who empowered Jesus' ministry continues to work through believers today, opening hearts to receive salvation and authenticating the Gospel message through signs, wonders, and miracles that demonstrate God's love and power in practical ways.\n\nWe engage culture as creative makers rather than mere critics, offering alternatives that reflect heaven's values while serving our neighborhoods, workplaces, and city with decisive acts of service and generous giving. The good news extends beyond Sunday gatherings into everyday life through practical demonstration of God's love combined with clear proclamation of His salvation, ensuring our communities experience the transformative power of the Gospel through both supernatural ministry and relational authenticity.\n\nThe Great Commission finds fulfillment through Spirit-empowered witnesses who make disciples rather than mere converts, establishing Spirit-filled communities that continue advancing God's kingdom through supernatural ministry and transformed lives. This mission flows from understanding our identity as God's representatives while serving others with humility and genuine care, creating pathways for meaningful contribution while standing for justice and with the marginalized.\n\nEvery believer carries God-given purpose that impacts the kingdom when fulfilled, recognizing that serving others with clear purpose, giving generously of our time, talent, and treasure, and sharing our faith creates opportunities for the Spirit to work while being good news to our neighborhoods, workplaces, and communities." },
        { title: "Our Historic Creeds", content: "We affirm our unity with the broader Body of Christ through the historic creeds that have guided Christian faith for centuries:\nThe Apostles' Creed - summarizing the foundational truths of our faith\nThe Nicene Creed - affirming the nature of Christ and the Trinity\nThe National Association of Evangelicals Statement of Faith - connecting us with the broader evangelical community\n\nThese historic statements anchor us in essential Christian doctrine while allowing liberty in non-essential matters, all bound together by love that creates unity without uniformity. We maintain theological clarity on essentials while extending charity in non-essentials, demonstrating kingdom-mindedness that transcends organizational barriers through cooperation with other Bible-believing churches for kingdom advancement." },
    ];
    
    const pageSections = [
        { label: 'Our Story', id: 'story' },
        { label: 'Our Beliefs', id: 'beliefs' },
        { label: 'Our Leadership', id: 'leadership' },
    ];


  return (
    <div className="animate-fade-in">
      <section className="bg-brand-secondary py-12">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="font-header font-extrabold text-5xl md:text-6xl tracking-tight">About Us</h1>
          <p className="font-accent italic text-2xl mt-2 text-gray-600">Founded in faith, rooted in relationship, and focused on transformation.</p>
        </div>
      </section>

      <SubNav links={pageSections} />

      <section id="story" className="py-20">
        <FadeInOnScroll>
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
              <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-12 items-center">
                  <div>
                    <h2 className="font-header font-extrabold text-4xl tracking-tight">Our Story</h2>
                    <div className="mt-6 text-lg text-gray-700 leading-relaxed space-y-4">
                        <p>
                          The Upper Room Fellowship began in 1971 when a group of believers gathered in an upper room above a veterinarian's office in Columbiana, Ohio. This location reflected the biblical Upper Room where Jesus' disciples gathered to pray and wait for the Holy Spirit.
                        </p>
                        <p>
                          United by a hunger for God's presence and a desire to experience authentic Christianity, they created a community where people could encounter God and build meaningful relationships.
                        </p>
                    </div>
                  </div>
                  <img src="https://images.unsplash.com/photo-1595183781333-31b0e1a53957?q=80&w=1974&auto=format&fit=crop" alt="Historic church building" className="rounded-lg shadow-xl w-full h-auto object-cover"/>
              </div>
               <div className="max-w-4xl mx-auto mt-12 text-lg text-gray-700 leading-relaxed space-y-4">
                    <p>
                      For over five decades, we've remained committed to being a church that transforms lives through the power of the Holy Spirit. What started as a small gathering has grown into a thriving community dedicated to pursuing healthy relationships, accessing abundant wholeness, knowing our greatness, owning a supernatural lifestyle, treasuring His presence, and living the Gospel.
                    </p>
                    <p>
                      Today, we continue helping people in our community discover their God-given purpose and experience the freedom and fullness Jesus promised. We believe God is calling us to greater impact as we serve Columbiana and beyond with the love and power of Jesus Christ.
                    </p>
                </div>
          </div>
        </FadeInOnScroll>
      </section>

       <section id="beliefs" className="py-20 bg-brand-light-gray">
        <FadeInOnScroll className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto">
                <h2 className="text-center font-header font-extrabold text-4xl tracking-tight">Our Beliefs</h2>
                <p className="text-center mt-4 text-lg text-gray-700 leading-relaxed mb-8">
                    We believe certain truths within Scripture form the essential foundation that unites God's people. While we may differ on non-essential matters, we are bound together by love. Right belief, championed by love, reflects what Jesus embodied.
                </p>
                <div className="mt-8 bg-white p-4 sm:p-8 rounded-lg shadow-md">
                    {beliefs.map(belief => (
                        <BeliefAccordion key={belief.title} title={belief.title}>
                            {belief.content.split('\n\n').map((paragraph, index) => <p key={index} className="mb-4 whitespace-pre-line">{paragraph}</p>)}
                        </BeliefAccordion>
                    ))}
                </div>
            </div>
        </FadeInOnScroll>
    </section>

      <section id="leadership" className="py-20">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
              <FadeInOnScroll>
                <h2 className="text-center font-header font-extrabold text-4xl tracking-tight">Our Leadership</h2>
              </FadeInOnScroll>
              <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-12">
                  {LEADERSHIP.map((member, index) => (
                    <FadeInOnScroll key={member.name} style={{ transitionDelay: `${index * 150}ms` }}>
                        <LeadershipCard member={member} />
                    </FadeInOnScroll>
                  ))}
              </div>
          </div>
      </section>

    </div>
  );
};

export default AboutUsPage;